GET http://localhost:3000/SOME1HING
###
GET http://localhost:3000/gban/check/13423422

###
PUT http://localhost:3000/gban/scan/
Content-Type: application/json

{
  "user_id": 13423422,
  "scanner": 32425,
  "reason": "sf432342dvs"
}
###
DELETE http://localhost:3000/gban/revert/13423422